version: '3'
services:
  core-crypto-converion:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    # entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: ./.docker/postgres
    tty: true
    environment:
      - POSTGRES_DB=crypto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9000:80'
    networks:
      - app-network

  # db:
  #   build: ./.docker/mysql
  #   restart: always
  #   tty: true
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql
  #     - ./.docker/mysql:/docker-entrypoint-initdb.d
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   networks:
  #     - app-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
